
name: Snyk Container
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check Docker image for vulnerabilities
      # Snyk can be used to break the build when it detects vulnerabilities.
      # In this case we want to upload the issues to GitHub Code Scanning
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        #REGISTRY: ghcr.io
        #IMAGE_NAME: ghcr.io/ho-cto/sre-monitoring-as-code:latest
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ghcr.io/ho-cto/sre-monitoring-as-code:b56eb15f24580edca66f4bc8ba1f1ae9b20e05cb
        args:  --app-vulns --nested-jars-depth=5 --file=./monitoring-as-code/Dockerfile --severity-threshold=medium
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
