name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: use snyk
        run: | 
          snyk container test ghcr.io/ho-cto/sre-monitoring-as-code:75d4a190e109a620b331d182f9e89fbf60190134 --app-vulns --nested-jars-depth=5 --file=./monitoring-as-code/Dockerfile --sarif-file-output=snyk.sarif
      - name: Use the Upload Artifact GitHub Action
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file:snyk.sarif
