name: Snyk Container
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '31 1 * * 1'
permissions: 
  contents: read
jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Container Scanning
      run: snyk container test -d ghcr.io/ho-cto/sre-monitoring-as-code:75d4a190e109a620b331d182f9e89fbf60190134 --app-vulns --nested-jars-depth=5 --file=./monitoring-as-code/Dockerfile  
      continue-on-error: true
    - name: Upload results to GitHub Container Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-container.sarif
