name: Snyk Container
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '31 1 * * 1'
permissions: 
  contents: read
jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - name: snyk install 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install snyk -g # install snyk
    - run: snyk -v
    - run: snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets
    - name: snyk container test 
    - run: snyk container test ghcr.io/ho-cto/sre-monitoring-as-code:75d4a190e109a620b331d182f9e89fbf60190134 --app-vulns --nested-jars-depth=5 --file=./monitoring-as-code/Dockerfile
    - name: Upload results to Github Code scanning 
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
